### ISSUE TITLE
Typo in definition of step in adequacy.v

### ISSUE THREAD

**Issue by hei411** [logsem/iris-tutorial#2]
The typo can be found [here](https://github.com/logsem/iris-tutorial/blob/9a5ee8194c6c61a20d19b1ee054595da27a34c00/exercises/adequacy.v#L41). 
Instead of σ1, it should be σ2, since the state of config2 changes.

Similarly, it should be changed in the adequacy.v file in theories/, i.e. [here](https://github.com/logsem/iris-tutorial/blob/9a5ee8194c6c61a20d19b1ee054595da27a34c00/theories/adequacy.v#L41)

**Comment by adamAndMath** [comment]
Fixed
